# Generated by Django 3.2.3 on 2021-05-31 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('roleID', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('roleName', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('memberID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=20)),
                ('fName', models.CharField(max_length=30)),
                ('mName', models.CharField(blank=True, max_length=30)),
                ('lName', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('picture', models.URLField(blank=True)),
                ('resID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurants.restaurant')),
                ('roleID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.role')),
            ],
            options={
                'db_table': 'member',
            },
        ),
    ]
