# Generated by Django 3.2.4 on 2021-06-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('AD', 'Admin'), ('EX', 'Executive'), ('MN', 'Manager'), ('ST', 'Staff'), ('ME', 'Member')], default='ME', max_length=3),
        ),
    ]
