# Generated by Django 3.2.3 on 2021-06-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('AD', 'admin'), ('EX', 'executive'), ('MN', 'manager'), ('ST', 'staff'), ('MB', 'member')], default='ME', max_length=3, null=True),
        ),
    ]
