# Generated by Django 3.2.3 on 2021-06-02 19:50

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='memberID',
            field=models.CharField(default=users.models.Member.genID, max_length=10, primary_key=True, serialize=False),
        ),
    ]
