# Generated by Django 3.2.4 on 2021-06-06 21:23

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_member_memberid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profilePic',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='static/images/%Y/%m/%d'),
        ),
    ]
