# Generated by Django 3.2.4 on 2021-06-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_member_memberid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='memberID',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
