# Generated by Django 3.2.4 on 2021-06-03 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_member_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='mName',
        ),
    ]
