# Generated by Django 3.2.4 on 2021-06-04 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_member_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='roleID',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
