# Generated by Django 3.2.4 on 2021-06-04 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0013_role'),
        ('users', '0003_alter_member_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='roleID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.role'),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
