# Generated by Django 3.2.4 on 2021-06-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_member_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('executive', 'executive'), ('manager', 'manager'), ('staff', 'staff'), ('member', 'member')], default='member', max_length=10),
        ),
    ]
