# Generated by Django 3.2.4 on 2021-06-05 21:04

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_member_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='avatars')),
                ('avatar_thumbnail', imagekit.models.fields.ProcessedImageField(upload_to='avatars')),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='profile',
            field=imagekit.models.fields.ProcessedImageField(upload_to='static/images/%Y/%m/%d'),
        ),
    ]
