# Generated by Django 3.2.4 on 2021-06-04 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_member_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='roleID',
        ),
    ]
