# Generated by Django 3.2.4 on 2021-06-06 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20210606_0404'),
        ('users', '0006_auto_20210606_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='companyID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurants.company'),
        ),
    ]
