# Generated by Django 3.2.4 on 2021-06-04 23:58

from django.db import migrations, models
import queueSystem.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('queueID', models.CharField(default=queueSystem.models.Queue.genID, max_length=10, primary_key=True, serialize=False)),
                ('peopleNum', models.IntegerField(default=0)),
                ('queueCreated', models.DateTimeField(auto_now_add=True)),
                ('reserveTime', models.DateTimeField(blank=True, null=True)),
                ('queueIsSuccess', models.CharField(choices=[('S', 'Success'), ('F', 'Fail'), ('W', 'Waiting'), ('C', 'Cancel'), ('P', 'Point')], default='W', max_length=10)),
                ('queueIsPass', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'queue',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('reviewID', models.CharField(default=queueSystem.models.Review.genID, max_length=10, primary_key=True, serialize=False)),
                ('detail', models.CharField(max_length=200)),
                ('rating', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'review',
            },
        ),
    ]
