# Generated by Django 3.2.4 on 2021-06-03 07:32

from django.db import migrations, models
import queueSystem.models


class Migration(migrations.Migration):

    dependencies = [
        ('queueSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='queueID',
            field=models.CharField(default=queueSystem.models.Queue.genID, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewID',
            field=models.CharField(default=queueSystem.models.Review.genID, max_length=10, primary_key=True, serialize=False),
        ),
    ]
