# Generated by Django 3.2.4 on 2021-06-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueSystem', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='queueIsSuccess',
            field=models.CharField(choices=[('S', 'Success'), ('F', 'Fail'), ('W', 'Waiting'), ('C', 'Cancel'), ('P', 'Point')], default='W', max_length=10),
        ),
    ]
