# Generated by Django 3.2.4 on 2021-06-05 22:40

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('queueSystem', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='reserveDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='queue',
            name='queueIsSuccess',
            field=models.CharField(choices=[('success', 'success'), ('fail', 'fail'), ('waiting', 'waiting'), ('cancel', 'cancel'), ('point', 'point')], default='waiting', max_length=10),
        ),
        migrations.AlterField(
            model_name='queue',
            name='reserveTime',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
