# Generated by Django 3.2.4 on 2021-06-07 02:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('queueSystem', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
