# Generated by Django 3.2.4 on 2021-06-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueSystem', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
