# Generated by Django 3.2.4 on 2021-06-05 23:38

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('queueSystem', '0003_auto_20210606_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='reserveDate',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='queue',
            name='reserveTime',
            field=models.TimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
