# Generated by Django 3.2.4 on 2021-06-04 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueSystem', '0003_alter_queue_queueissuccess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='queueIsCome',
        ),
        migrations.AddField(
            model_name='queue',
            name='queueIsPass',
            field=models.BooleanField(default=False),
        ),
    ]
