# Generated by Django 3.2.4 on 2021-06-06 11:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('queueSystem', '0004_auto_20210606_0638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='reserveDate',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='reserveTime',
        ),
        migrations.AddField(
            model_name='queue',
            name='reserveDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
