# Generated by Django 3.2.3 on 2021-05-31 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=20)),
                ('minuteWait', models.IntegerField()),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('companyID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('categoryNameTH', models.CharField(max_length=30)),
                ('categoryNameEN', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=20)),
                ('subDistrict', models.CharField(blank=True, max_length=20)),
                ('district', models.CharField(blank=True, max_length=20)),
                ('province', models.CharField(max_length=20)),
                ('postalCode', models.CharField(max_length=5)),
                ('email', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=10)),
                ('picture', models.URLField(blank=True)),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('resID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('resNameTH', models.CharField(max_length=30)),
                ('resNameEN', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=20)),
                ('subDistrict', models.CharField(blank=True, max_length=20)),
                ('district', models.CharField(blank=True, max_length=20)),
                ('province', models.CharField(max_length=20)),
                ('postalCode', models.CharField(max_length=5)),
                ('email', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=10)),
                ('picture', models.URLField(blank=True, null=True)),
                ('categoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.category')),
                ('companyID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurants.company')),
            ],
            options={
                'db_table': 'Restaurant',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menuID', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('menuNameTH', models.CharField(max_length=20)),
                ('menuNameEN', models.CharField(max_length=20)),
                ('description', models.TextField(null=True)),
                ('price', models.FloatField()),
                ('avaliable', models.BooleanField()),
                ('picture', models.URLField(blank=True, null=True)),
                ('resID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant')),
            ],
            options={
                'db_table': 'menu',
            },
        ),
    ]
