# Generated by Django 3.2.4 on 2021-06-07 05:55

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import restaurants.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryID', models.CharField(default=restaurants.models.Category.genID, max_length=10, primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=20)),
                ('minuteWait', models.IntegerField()),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('companyID', models.CharField(default=restaurants.models.Company.genID, max_length=10, primary_key=True, serialize=False)),
                ('companyName', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=20)),
                ('subDistrict', models.CharField(blank=True, max_length=20)),
                ('district', models.CharField(blank=True, max_length=20)),
                ('province', models.CharField(max_length=20)),
                ('postalCode', models.CharField(max_length=5)),
                ('email', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=10)),
                ('profilePic', imagekit.models.fields.ProcessedImageField(upload_to='static/images/%Y/%m/%d')),
            ],
            options={
                'db_table': 'Company',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('resID', models.CharField(default=restaurants.models.Restaurant.genID, max_length=10, primary_key=True, serialize=False)),
                ('resName', models.CharField(max_length=30)),
                ('open', models.TimeField()),
                ('close', models.TimeField()),
                ('address', models.CharField(max_length=20)),
                ('subDistrict', models.CharField(blank=True, max_length=20)),
                ('district', models.CharField(blank=True, max_length=20)),
                ('province', models.CharField(max_length=20)),
                ('postalCode', models.CharField(max_length=5)),
                ('email', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=10)),
                ('profilePic', imagekit.models.fields.ProcessedImageField(upload_to='static/images/%Y/%m/%d')),
                ('coverPic', imagekit.models.fields.ProcessedImageField(upload_to='static/images/%Y/%m/%d')),
                ('categoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.category')),
                ('companyID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurants.company')),
            ],
            options={
                'db_table': 'Restaurant',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menuID', models.CharField(default=restaurants.models.Menu.genID, max_length=15, primary_key=True, serialize=False)),
                ('menuName', models.CharField(max_length=20)),
                ('description', models.TextField(null=True)),
                ('price', models.FloatField()),
                ('avaliable', models.BooleanField()),
                ('profilePic', imagekit.models.fields.ProcessedImageField(upload_to='static/images/%Y/%m/%d')),
                ('resID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant')),
            ],
            options={
                'db_table': 'menu',
            },
        ),
    ]
