# Generated by Django 3.2.3 on 2021-06-02 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='categoryNameEN',
            new_name='companyNameEN',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='categoryNameTH',
            new_name='companyNameTH',
        ),
    ]
