# Generated by Django 3.2.4 on 2021-06-04 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20210605_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='coverPic',
            field=models.ImageField(default='static/images/defaultProfile.png', upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='profilePic',
            field=models.ImageField(default='static/images/defaultProfile.png', upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='coverPic',
            field=models.ImageField(default='static/images/defaultProfile.png', upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='profilePic',
            field=models.ImageField(default='static/images/defaultProfile.png', upload_to='static/images/'),
        ),
    ]
