# Generated by Django 3.2.4 on 2021-06-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20210607_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
