# Generated by Django 3.2.4 on 2021-06-07 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_company_success'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='success',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='success',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
