# Generated by Django 3.2.4 on 2021-06-03 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_auto_20210603_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='companyNameTH',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='menuNameTH',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='resNameTH',
        ),
    ]
