# Generated by Django 3.2.4 on 2021-06-03 07:32

from django.db import migrations, models
import restaurants.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_auto_20210603_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categoryID',
            field=models.CharField(default=restaurants.models.Category.genID, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='companyID',
            field=models.CharField(default=restaurants.models.Company.genID, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menuID',
            field=models.CharField(default=restaurants.models.Menu.genID, max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='resID',
            field=models.CharField(default=restaurants.models.Restaurant.genID, max_length=10, primary_key=True, serialize=False),
        ),
    ]
