# Generated by Django 3.2.4 on 2021-06-03 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_auto_20210603_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='companyNameEN',
            new_name='companyName',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='menuNameEN',
            new_name='menuName',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='resNameEN',
            new_name='resName',
        ),
    ]
