# Generated by Django 3.2.4 on 2021-06-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_auto_20210603_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='mapLAT',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='mapLon',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
